version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
     - "9090:9090"
    volumes:
      - ./:/app

  test:
    environment:
      FLASK_DEBUG: 1
    build:
      context: .
      dockerfile: Dockerfile
    command: ["bin/test.sh"]
    volumes:
      - ./:/app

  lint-flake8:
    build:
      context: .
      dockerfile: Dockerfile
    command: flake8 .

  lint-black:
    build:
      context: .
      dockerfile: Dockerfile
    command: black . --check --diff
