runtime: python
env: flex
entrypoint: bash -c 'flask db upgrade && gunicorn -w 4 -b :$PORT app.wsgi:app'
runtime_config:
  python_version: 3.7
env_variables:
  FLASK_ENV: production

beta_settings:
  cloud_sql_instances: conversionly-235308:europe-west1:conversionly-cloud-sql

manual_scaling:
  instances: 2
resources:
  cpu: 1
  memory_gb: 5
  disk_size_gb: 10

readiness_check:
  path: '/health'
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

includes:
- secrets.yaml
