FROM python:3.7-slim
ENV PYTHONUNBUFFERED=1

COPY ./requirements.txt /app/requirements.txt
# Downgrade pip to avoid a dependency resolver bug https://github.com/pypa/pip/issues/9187
RUN pip install pip==20.2
RUN pip install -r /app/requirements.txt

COPY . /app
WORKDIR /app

CMD flask rq worker
